services:
  django:
    build: ./django_backend
    container_name: django
    depends_on:
      - postgres
    volumes:
      - ./django_backend:/app
    env_file: .env
    ports:
      - "8000:8000"
    
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: