# Generated by Django 5.2.6 on 2025-09-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_tasktemplate_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Low priority'), ('medium', 'Medium priority'), ('high', 'High priority')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'Task pending to be done'), ('in_progress', 'Task in progress'), ('done', 'Completed task')], default='todo', max_length=20),
        ),
    ]
